// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqsylFzKKWiiG8zuLkB5GP87cNKhPX65U',
    appId: '1:858080245129:web:3c05c1ebd7fd01e2631d58',
    messagingSenderId: '858080245129',
    projectId: 'ejercicio-de-practica-c2a5b',
    authDomain: 'ejercicio-de-practica-c2a5b.firebaseapp.com',
    databaseURL: 'https://ejercicio-de-practica-c2a5b-default-rtdb.firebaseio.com',
    storageBucket: 'ejercicio-de-practica-c2a5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO12z1tFP-96kub__D1bB7LBcvC5Qi_mU',
    appId: '1:858080245129:android:ebfdec605cfefd2d631d58',
    messagingSenderId: '858080245129',
    projectId: 'ejercicio-de-practica-c2a5b',
    databaseURL: 'https://ejercicio-de-practica-c2a5b-default-rtdb.firebaseio.com',
    storageBucket: 'ejercicio-de-practica-c2a5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2KuLxAZmcGA4WRJg4AS7dnCb3dIorNA',
    appId: '1:858080245129:ios:2661c7d25dd9e35e631d58',
    messagingSenderId: '858080245129',
    projectId: 'ejercicio-de-practica-c2a5b',
    databaseURL: 'https://ejercicio-de-practica-c2a5b-default-rtdb.firebaseio.com',
    storageBucket: 'ejercicio-de-practica-c2a5b.appspot.com',
    iosBundleId: 'com.example.flutterApp06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR2KuLxAZmcGA4WRJg4AS7dnCb3dIorNA',
    appId: '1:858080245129:ios:2661c7d25dd9e35e631d58',
    messagingSenderId: '858080245129',
    projectId: 'ejercicio-de-practica-c2a5b',
    databaseURL: 'https://ejercicio-de-practica-c2a5b-default-rtdb.firebaseio.com',
    storageBucket: 'ejercicio-de-practica-c2a5b.appspot.com',
    iosBundleId: 'com.example.flutterApp06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqsylFzKKWiiG8zuLkB5GP87cNKhPX65U',
    appId: '1:858080245129:web:3019ced76230530b631d58',
    messagingSenderId: '858080245129',
    projectId: 'ejercicio-de-practica-c2a5b',
    authDomain: 'ejercicio-de-practica-c2a5b.firebaseapp.com',
    databaseURL: 'https://ejercicio-de-practica-c2a5b-default-rtdb.firebaseio.com',
    storageBucket: 'ejercicio-de-practica-c2a5b.appspot.com',
  );
}